version: '3.8'
name: kgs-docs

services:
  api.app:
    container_name: kgs-docs.app
    image: kgs-docs.app
    build:
      context: .
      dockerfile: Api.App/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  efdata:
    container_name: kgs-docs.efdata
    image: kgs-docs.efdata
    build:
      context: .
      dockerfile: Api.EFData/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    container_name: kgs-docs.postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}"]
      timeout: 1s
      retries: 7
    ports:
      - 5432:5432

  pgadmin:
    container_name: kgs-docs.pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgresql.org
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres